// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEszjrq9kwm7xwj9Z5j69Mxoj1KtNwWus',
    appId: '1:468637029356:web:68d8fb014cccbd46ece6c9',
    messagingSenderId: '468637029356',
    projectId: 'login-lite-3c0c9',
    authDomain: 'login-lite-3c0c9.firebaseapp.com',
    storageBucket: 'login-lite-3c0c9.appspot.com',
    measurementId: 'G-LE2MY6RER9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSLif8BahG-6rFGBvweoYlo5j-pRs7nHo',
    appId: '1:468637029356:android:8a7bc65ab79f9dfcece6c9',
    messagingSenderId: '468637029356',
    projectId: 'login-lite-3c0c9',
    storageBucket: 'login-lite-3c0c9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoOlZfrW6e_5Vdp3GWg63Vap91I-Cwv-k',
    appId: '1:468637029356:ios:90392fa24db13c05ece6c9',
    messagingSenderId: '468637029356',
    projectId: 'login-lite-3c0c9',
    storageBucket: 'login-lite-3c0c9.appspot.com',
    iosClientId: '468637029356-tuuun44q02titliql9bl5dd24h3ef7tg.apps.googleusercontent.com',
    iosBundleId: 'com.aveosoftware.loginlite.loginLite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoOlZfrW6e_5Vdp3GWg63Vap91I-Cwv-k',
    appId: '1:468637029356:ios:90392fa24db13c05ece6c9',
    messagingSenderId: '468637029356',
    projectId: 'login-lite-3c0c9',
    storageBucket: 'login-lite-3c0c9.appspot.com',
    iosClientId: '468637029356-tuuun44q02titliql9bl5dd24h3ef7tg.apps.googleusercontent.com',
    iosBundleId: 'com.aveosoftware.loginlite.loginLite',
  );
}
